//--- GI MODEL

export interface GiModel {
  _id: string,
  codigo: string,
  razon_social: string,
  nombre_fantasia: string,
  rubro_principal: string,
  actividad_principal: string,
  rubro_secundario: string,
  actividad_secundaria: string,
  grupo_interes: string,
  categoria: string,
  categoria_empresa: string,
  categoria_cliente: string,
  fecha_inic_mac: string,
  edad_gi: number,
  contacto: number,
  contacto_2: number,
  email_central: string,
  email_encargado: string,
  profesion_oficio: string,
  direccion: string,
  localidad: string,
  comuna: string,
  provincia: string,
  region: string,
  sector: string,
  nacionalidad: string,
  pais_origen: string,
  grado_formalizacion: string,
  nro_contrato: any,
  credito: string,
  dias_credito: number,
  orden_compra: string,
  url_file_adjunto: any,
  activo_inactivo: boolean,
  contrato_faenas?: any,
  imagen_perfil_gi?: string,
  licencia_conduccion?: string,
  nivel_educacional?: string,
  rol: string
}