export const ausencesInitialization = {
    _id: '',
    id_empleado: '',
    fecha_inicio_ausencia: '',
    hora_inicio_ausencia: '08:30',
    fecha_fin_ausencia: '',
    hora_fin_ausencia: '18:30',
    tipo_ausencia: '',
    abrev_ausencia: '',
    color_ausencia: '',
    descripcion: '',
    mes_ausencia: '',
    anio_ausencia: '',
    cantidad_dias: 0,
    fechas: [''],
    archivo_adjunto: '',
}
