export const ExistenceInitialization = {
    _id: '',
    categoria_general: '',
    subcategoria_uno: '',
    subcategoria_dos: '',
    subcategoria_tres: '',
    codigo_categoria_tres: '',
    entradas: 0,
    salidas: 0,
    existencia: 0,
    cantMaxima: 0,
    costo_total: 0,
    costo_total_string: '',
    costo_unitario_promedio: 0,
    costo_unitario_promedio_string: '',
    estado: '',
}
