export const EntriesInitialization = {
    _id: '',
    nombre_proveedor: '',
    categoria_general: '',
    subcategoria_uno: '',
    subcategoria_dos: '',
    subcategoria_tres: '',
    codigo_categoria_tres: '',
    cant_maxima_categoria_tres: 0,
    detalle: '',
    cantidad: 0,
    porcentaje_impuesto: 0,
    valor_impuesto: 0,
    costo_unitario: 0,
    costo_total: 0,
}

export const ExpensesInitialization = {
    _id: '',
    codigo: '',
    fecha: '',
    fecha_registro: '',
    categoria_general: '',
    subcategoria_uno: '',
    subcategoria_dos: '',
    descripcion_gasto: '',
    id_proveedor: '',
    rut_proveedor: '',
    categoria_proveedor: '',
    razon_social_proveedor: '',
    requiere_servicio: '',
    id_servicio: '',
    servicio: '',
    tipo_registro: '',
    tipo_documento: '',
    nro_documento: '',
    medio_pago: '',
    institucion_bancaria: '',
    inventario: '',
    cantidad_factor: 0,
    precio_unitario: 0,
    monto_neto: 0,
    impuesto: 0,
    exento: 0,
    total: 0,
    total_string: '',
    observaciones: '',
    archivo_adjunto: '',
    entradas: [],
    isActive: true,
}
