export const RequestPaymentInitialization = {
  _id: '',
  codigo: '',
  nombre_servicio: '',
  faena_seleccionada_cp: '',
  valor_servicio: 0,
  valor_servicio_string: '',
  categoria_cliente: '',
  fecha_facturacion: '',
  dias_credito: 0,
  rut_cp: '',
  razon_social_cp: '',
  rut_cs: '',
  razon_social_cs: '',
  lugar_servicio: '',
  sucursal: '',
  estado: '',
  valor_cancelado: 0,
  valor_cancelado_string: '',
  valor_deuda: 0,
  valor_deuda_string: '',
  cartas_cobranza: '',
  isActive: true
}