export const ReservationInitialization = {
  _id: '',
  codigo: '',
  id_GI_Principal: '',
  id_GI_Secundario: '',
  id_GI_personalAsignado: '',
  faena_seleccionada_cp: '',
  valor_servicio: 0,
  rut_cp: '',
  razon_social_cp: '',
  rut_cs: '',
  razon_social_cs: '',
  fecha_reserva: '',
  hora_reserva: '',
  fecha_reserva_fin: '',
  hora_reserva_fin: '',
  jornada: '',
  mes: '',
  anio: '',
  nombre_servicio: '',
  lugar_servicio: '',
  sucursal: '',
  url_file_adjunto: {},
  observacion: [],
  estado: '',
  isActive: true
}